import type { Metadata } from "next";
import "./globals.css";
import FormResponseProvider from "@/lib/providers/FormResponseProvider";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Authjs Impl",
  description: "Generated by create next app",
};

export default function RootLayout(
  { children }: Readonly<{ children: React.ReactNode }>) 
{
  return (
    <html lang="en">
      <body className={`antialiased`}>
      <FormResponseProvider>
        <Navbar/>
        {children}
      </FormResponseProvider>
      </body>
    </html>
  );
}
